# add stages here 
stages:
  prepare_data:
    cmd: python src/stage_01_prepare_data.py --config=configs/config.yaml
    deps:
    - src/stage_01_prepare_data.py
    - data/training.1600000.processed.noemoticon.csv
    - configs/config.yaml
    - src/utils/common.py
    outs:
    - artifacts/prepared/dataset.csv
