# add stages here 
stages:
  prepare_data:
    cmd: python src/stage_01_prepare_data.py --config=configs/config.yaml
    deps:
    - src/stage_01_prepare_data.py
    - data/training.1600000.processed.noemoticon.csv
    - configs/config.yaml
    - src/utils/common.py
    outs:
    - artifacts/prepared/dataset.csv

  data_preprocess:
    cmd: python src/stage_02_data_preprocess.py --config=configs/config.yaml --params=params.yaml
    deps:
    - src/stage_02_data_preprocess.py
    - artifacts/prepared/dataset.csv
    - configs/config.yaml
    - src/utils/common.py
    - src/utils/data_management.py
    params:
    - preprocess.split
    - preprocess.seed
    - preprocess.buffer_size
    - preprocess.batch_size
    outs:
    - artifacts/preprocessed/train.tfrecord
    - artifacts/preprocessed/test.tfrecord
  
  train:
    cmd: python src/stage_03_train.py --config=configs/config.yaml --params=params.yaml
    deps:
    - artifacts/preprocessed/train.tfrecord
    - artifacts/preprocessed/test.tfrecord
    - configs/config.yaml
    - src/utils/common.py
    - src/utils/models.py
    params:
    - train.vocab_size
    - train.output_dim
    - train.epochs
    - train.lstm_units
    - train.validation_steps
    outs:
    - artifacts/train
    