# It contains all the configs required in the project

source_data:
  data_dir: data
  data_file: training.1600000.processed.noemoticon.csv

artifacts:
  ARTIFACTS_DIR: artifacts
  PREPARED_DATA: prepared
  DATASET_FILE: dataset.csv
