# It contains all the configs required in the project

source_data:
  data_dir: data
  data_file: training.1600000.processed.noemoticon.csv

artifacts:
  ARTIFACTS_DIR: artifacts
  PREPARED_DATA: prepared
  DATASET_FILE: dataset.csv
  PREPROCESSED_DATA: preprocessed
  TRAIN_DATA: train.tfrecord
  TEST_DATA: test.tfrecord
  TRAIN_DIR: train
  CHECKPOINT_DIR: ckpt
  CHECKPOINT_MODEL: model
  TB_ROOT_LOG_DIR: tb_log_dir
  MODEL_DIR: model
  MODEL_FILE: model_full.h5
